nft sync bug fix
bianjieai/irita-explorer-backend pull request #48
Opened 2020-11-11 07:16 UTC by lsc949982212

2020-11-11 10:21 UTC, hangts commented on src/task/nft.task.service.ts
> +                nftObj[idStr].create_time = getTimestamp();
create_time 逻辑错误

2020-11-11 10:28 UTC, lsc949982212 commented on src/schema/tx.schema.ts
> +                msgs:1,
msgs中除了recipient字段, 其他字段都用得到, 所以msgs取全部值

2020-11-11 11:10 UTC, hangts commented on src/schema/tx.schema.ts
> +                msgs:1,
多Message下 msgs中会存在非[{'msgs.type':TxType.mint_nft},{'msgs.type':TxType.edit_nft},
 {'msgs.type':TxType.transfer_nft},{'msgs.type':TxType.burn_nft}]类型的msg,需要指定字段过滤。

2020-11-11 11:33 UTC, hangts commented on README.md
> +- INTERVAL_HEIGHT `Optional` `number` interval height for sync nft (default 1000)
INCREASE_HEIGHT、INTERVAL_HEIGHT 统一成一个配置，否则INCREASE_HEIGHT、INTERVAL_HEIGHT若配置不一致会导致同步错误

2020-11-12 01:15 UTC, lsc949982212 commented on src/task/nft.task.service.ts
> +            const nftTxList: ITxStruct[] = await this.queryNftTxList(lastBlockHeight);
判断逻辑已重新更新

2020-11-12 01:35 UTC, hangts commented on src/schema/tx.schema.ts
> +            }
冗余的$match

2020-11-12 02:02 UTC, hangts approved these changes

2020-11-12 03:21 UTC, kaifei-bianjie requested changes

2020-11-12 03:21 UTC, kaifei-bianjie commented on src/config/config.ts
> +        maxOperateTxCount: MAX_OPERATE_TX_COUNT || 1000,
MAX_OPERATE_TX_COUNT default value set to `100`

2020-11-12 05:54 UTC, kaifei-bianjie approved these changes

2020-11-12 05:54 UTC, merged