fix task-nft、task-idnetity
bianjieai/irita-explorer-backend pull request #77
Opened 2020-12-11 07:34 UTC by duanjie-cmd

2020-12-11 08:18 UTC, hangts approved these changes

2020-12-11 10:12 UTC, hangts approved these changes

2020-12-14 03:50 UTC, kaifei-bianjie requested changes

2020-12-14 03:50 UTC, kaifei-bianjie commented on src/helper/task.helper.ts
> +    return count > 0
`return count == 1`

2020-12-14 05:37 UTC, kaifei-bianjie approved these changes

2020-12-14 05:37 UTC, merged