add index and optimize queries
bianjieai/irita-explorer-backend pull request #81
Opened 2020-12-14 10:41 UTC by jinbiao-bianjie

2020-12-14 10:49 UTC, kaifei-bianjie requested changes

2020-12-14 10:49 UTC, kaifei-bianjie commented on src/schema/identity.schema.ts
> +      queryParameters.$in = [
这能使用 in 替代 or 查询？

2020-12-14 10:49 UTC, kaifei-bianjie commented on src/schema/validators.schema.ts
> +ValidatorSchema.index({jailed: 1})
为什么不建立 `jailed: -1, status: -1` 这样的联合索引?

2020-12-14 11:41 UTC, jinbiao-bianjie commented on src/schema/identity.schema.ts
> +      queryParameters.$in = [
由于是模糊查询，且查询的是两个条件中的某一个。所以还是用or查询。

2020-12-15 02:56 UTC, hangts approved these changes

2020-12-15 03:01 UTC, kaifei-bianjie approved these changes

2020-12-15 03:02 UTC, merged