update statistics
bianjieai/irita-explorer-backend pull request #89
Opened 2020-12-16 09:10 UTC by duanjie-cmd

2020-12-16 09:22 UTC, lsc949982212 commented on src/service/statistics.service.ts
> +            '200': this.queryLatestHeightAndTimeAndValidator(latestBlock),
对象值存储对方法的引用, 不要直接调用, 需要promise执行的时候再调用

2020-12-16 09:24 UTC, lsc949982212 commented on src/service/statistics.service.ts
> +            result.latestBlockTime = new Date(latestBlock.block.header.time || '').getTime() / 1000;
Math.floor或者Math.ceil一下

2020-12-16 09:26 UTC, lsc949982212 commented on src/service/statistics.service.ts
> +            result.moniker = (validators[0].description && validators[0].description.moniker) || '';
validators空数组判断

2020-12-16 09:30 UTC, kaifei-bianjie requested changes

2020-12-16 09:30 UTC, kaifei-bianjie commented on src/service/statistics.service.ts
> +    async queryLatestHeightAndTimeAndValidator(latestBlock?:any): Promise<{height:number,latestBlockTime:number,moniker:string,validator_icon:string,operator_addr:string} | null> {
`queryLatestHeightAndTimeAndValidator` 放在 lcd 查询的方法里

2020-12-16 09:30 UTC, kaifei-bianjie commented on src/controller/statistics.controller.ts
> +    @Get('/pledge_rate')
rename to `/statistics/network`

2020-12-16 09:30 UTC, kaifei-bianjie commented on src/controller/statistics.controller.ts
> +    async queryPledgeRate(): Promise<Result<PledgeRateResDto>> {
- queryPledgeRate rename to queryNetworkStatistics
- queryNetworkStatistics should have `query` param

2020-12-16 09:30 UTC, kaifei-bianjie commented on src/controller/statistics.controller.ts
>      @Get()
- router path rename to `/statistics/db`

2020-12-16 10:37 UTC, hangts commented on src/service/statistics.service.ts
> +        let validators = await this.stakingValidatorsModel.queryAllValidators();
validator = find({proposer_address:xxx})

2020-12-16 10:37 UTC, hangts commented on src/service/statistics.service.ts
> +        const Correlation:object = {
事件不用预先定义，循环事件列表，各个事件使用switch做个分发。

2020-12-17 01:48 UTC, hangts approved these changes

2020-12-18 01:53 UTC, kaifei-bianjie approved these changes

2020-12-18 01:53 UTC, merged