R4R: add staking validators
bianjieai/irita-explorer-backend pull request #9
Opened 2020-09-15 09:49 UTC by jinbiao-bianjie

2020-09-17 08:48 UTC, kaifei-bianjie requested changes

2020-09-17 08:48 UTC, kaifei-bianjie commented on src/http/lcd/staking.validator.http.ts
> +    async queryValidatorListFromLcd(pageNum:number,pageSize:number){
define lcd result struct and return @jinbiao-bianjie

2020-09-18 11:41 UTC, hangts commented on src/task/parameters.task.service.ts
> +        }
1.needInsertData isArray  逻辑错误

2020-09-18 11:41 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +            allValidatorsFromLcd = allValidatorsFromLcd.concat(allValidatorsFromLcd)
逻辑错误

2020-09-18 11:41 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +            for (let key of validatorsFromDbMap.keys()) {
for 循环体逻辑错误

2020-09-18 11:41 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +                if (!allValidatorsFromLcdMap.has(key)) {
for循环逻辑错误

2020-09-18 11:41 UTC, hangts commented on src/util/util.ts
> +    prefix = prefix || 'rbid';
'rbid' ？？

2020-09-21 11:34 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +                    needDeleteValidatorDbMap.set(validatorsFromDbMap.get(key).operator_address, needDeleteValidatorDbMap)
needDeleteValidatorDbMap.set(validatorsFromDbMap.get(key).operator_address, needDeleteValidatorDbMap） 逻辑错误

2020-09-21 11:44 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +                    needInsertOrUpdate.set(validatorWithUpdateTime.operator_address, validatorWithUpdateTime)
needInsertOrUpdate.set(validatorWithUpdateTime.operator_address, validatorWithUpdateTime) 逻辑错误

2020-09-21 11:44 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +            for (let key of validatorsFromDbMap.keys()) {
主循环lcd最新数据

2020-09-21 11:44 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +                    allValidatorsFromLcdMap.forEach(item => {
逻辑错误

2020-09-22 02:34 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +            allValidatorsFromLcd = [...nextPageValidatorsFromLcd]
allValidatorsFromLcd = [...nextPageValidatorsFromLcd] 逻辑错误

2020-09-22 02:34 UTC, hangts commented on src/task/staking.validator.task.service.ts
> +        if (allValidatorsFromLcdMap.size !== 0 && validatorsFromDbMap.size !== 0) {
if (allValidatorsFromLcdMap.size !== 0 && validatorsFromDbMap.size !== 0) 改成 if (validatorsFromDbMap.size !== 0)

2020-09-22 02:39 UTC, jinbiao-bianjie commented on src/task/staking.validator.task.service.ts
> +        if (allValidatorsFromLcdMap.size !== 0 && validatorsFromDbMap.size !== 0) {
我觉得从lcd请求回来没有数据就不用去做下面的循环逻辑了  这个是删除的逻辑 只有两个都有数据的时候才会进行对比删除

2020-09-22 02:59 UTC, hangts approved these changes

2020-09-22 04:01 UTC, merged